import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layouts/Header";
import ResponsiveHeader from "@/components/layouts/ResponsiveHeader";
import PopularManga from "@/components/layouts/PopularManga";
import Footer from "@/components/layouts/Footer";
import BackToTop from "@/components/layouts/BackToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aisumanga (Mangakakalot Clone)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-[#e9eaed] w-full h-full min-h-screen overflow-x-hidden pt-8">
        <Header />
        <ResponsiveHeader />
        <PopularManga />
        {children}
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
